version: '3.9'
services:
        py3:
                build:
                        context: ./py3
                        dockerfile: Dockerfile
                restart: always
                entrypoint: >
                        jupyter-lab
                        --allow-root
                        --ip=*
                        --port=9595
                        --no-browser
                        --NotebookApp.token=''
                        --notebook-dir=/workspace
                ports:
                        - "9595:9595"
                volumes:
                        - ./py3/root_jupyter:/root/.jupyter
                        - ./workspace:/workspace

                environment:
                        - "NVIDIA_VISIBLE_DEVICES=all"
                        - "NVIDIA_DRIVER_CAPABILITIES=all"
                deploy:
                        resources:
                                reservations:
                                        devices:
                                                - capabilities:
                                                        - gpu